NODE_NAME="airflow-img-${BUILD_NUMBER}"
NODE_TMPL="docker/ubuntu.m1.medium.yaml"

if (GERRIT_EVENT_TYPE == 'change-merged') {
    IMAGE_TAG = "0.1.0-${GERRIT_CHANGE_NUMBER}"
    AIRFLOW_IMAGE_NAME = "ucp/airflow"
}else{
    IMAGE_TAG = "${GERRIT_CHANGE_NUMBER}.${GERRIT_PATCHSET_NUMBER}"
    AIRFLOW_IMAGE_NAME = "ucp-patchset/airflow"
}

currentBuild.displayName = "${GERRIT_EVENT_TYPE}-${BUILD_NUMBER}"
vm(NODE_NAME, NODE_TMPL) {
    stage('Checkout'){
        gerrithub.clone("att-comdev/shipyard", GERRIT_REFSPEC)
    }
    stage('Docker Build') {
        timeout(20){
            parallel (
                "stream shipyard" : {
                node(NODE_NAME){
                    dir("airflow"){
                        sh  "make build_shipyard IMAGE_TAG=${IMAGE_TAG}"
                    }
            }
        },
                "stream airflow" : {
                node(NODE_NAME){
                    dir("airflow"){
                        sh  '''make build_airflow \
                            AIRFLOW_IMAGE_NAME=${AIRFLOW_IMAGE_NAME} \
                            IMAGE_TAG=${IMAGE_TAG}'''
                    }
                }
            })
        }
    }
    stage('Docker Run') {
        timeout(20){
            parallel (
                "stream run_shipyard" : {
                    node(NODE_NAME){
                        dir("airflow"){
                            sh  "make run_shipyard IMAGE_TAG=${IMAGE_TAG}"
                    }
                }
            },
                "stream run_airflow" : {
                    node(NODE_NAME){
                        dir("airflow"){
                            sh  '''make run_airflow \
                                AIRFLOW_IMAGE_NAME=${AIRFLOW_IMAGE_NAME} \
                                IMAGE_TAG=${IMAGE_TAG}'''
                    }
                }
            })
        }
    }
    stage('Publish'){
            NAME="${AIRFLOW_IMAGE_NAME}:${IMAGE_TAG}"
//            publish.artifactory(NAME,NAME)

        if (GERRIT_EVENT_TYPE == 'change-merged') {
            LATEST = "ucp/airflow:latest"
//            publish.artifactory(FULL_NAME,LATEST)
        }
    }
}