NODE_NAME="airflow-img-${BUILD_NUMBER}"
NODE_TMPL="docker/ubuntu.m1.medium.yaml"

if (GERRIT_EVENT_TYPE == 'change-merged') {
    AIRFLOW_IMAGE_NAME = 'ucp/airflow'
    IMAGE_TAG = "0.1.0-${GERRIT_CHANGE_NUMBER}"
}else{
    AIRFLOW_IMAGE_NAME = 'ucp-patchset/airflow'
    IMAGE_TAG = "${GERRIT_CHANGE_NUMBER}.${GERRIT_PATCHSET_NUMBER}"
}

currentBuild.displayName = "#${BUILD_NUMBER}-${GERRIT_EVENT_TYPE}"
vm(NODE_NAME, NODE_TMPL) {
    stage('Checkout'){
        gerrithub.clone('att-comdev/shipyard', GERRIT_REFSPEC)
    }
    stage('Docker Build') {
        sh """make build_shipyard IMAGE_TAG=${IMAGE_TAG}
              make build_airflow \
              AIRFLOW_IMAGE_NAME=${AIRFLOW_IMAGE_NAME} \
              IMAGE_TAG=${IMAGE_TAG}"""
    }
    stage('Docker Run') {
        sh """make run_shipyard IMAGE_TAG=${IMAGE_TAG}
              make run_airflow \
              AIRFLOW_IMAGE_NAME=${AIRFLOW_IMAGE_NAME} \
              IMAGE_TAG=${IMAGE_TAG}"""
    }
    stage('Publish'){
        NAME="${AIRFLOW_IMAGE_NAME}:${IMAGE_TAG}"
        publish.artifactory(NAME,NAME)
        if (GERRIT_EVENT_TYPE == 'change-merged') {
            LATEST = "ucp/airflow:latest"
            publish.artifactory(NAME,LATEST)
            QUAY_LATEST="attcomdev/airflow:latest"
            publish.quay(NAME,QUAY_LATEST)
        }
    }
}