JENKINS_VM_LAUNCH='local-vm-launch'
NODE_NAME="${JOB_BASE_NAME}-${BUILD_NUMBER}"
NODE_TMPL="docker/ubuntu.m1.medium.yaml"

vm(NODE_NAME, NODE_TMPL) {
   stage('Test getImageDigest'){
      sh "echo " + params.image
   }
}
