node('master') {
	stage('Test Property'){
    	sh "echo PARAM1: " + PARAM1
    	sh "echo PARAM2: " + PARAM2
    	sh "echo PARAM3: " + PARAM3
    }
	stage('Test Property inside wrapper - 1'){
		wrap([$class: 'MaskPasswordsBuildWrapper']) {
			sh "echo PARAM1: " + PARAM1
			sh "echo PARAM2: " + PARAM2
			sh "echo PARAM3: " + PARAM3
	   }
	stage('Test Property inside wrapper - 2'){
		wrap([$class: 'MaskPasswordsBuildWrapper', varPassworPairs: [[var: 'PARAM1', password: PARAM1],[var: 'PARAM2', password: PARAM2],[var: 'PARAM3', password: PARAM3]]]) {
			sh "echo PARAM1: " + PARAM1
			sh "echo PARAM2: " + PARAM2
			sh "echo PARAM3: " + PARAM3
	   }
   }
}
