node {
   stage('Artifactory property') {
      sh "echo Artifactory property"
      sh "echo ${url}"
      sh "echo ${prop}"
      
   }
   stage('Docker') {
      sh "echo Docker"
      build.getImageDigest("${image}")
   }
}



pipeline {
    agent any 
    stages {
        stage('Test setProperty') {
            steps {
                sh "echo URL: " + params.url
                sh "echo Properties: " + params.prop
                publish.setProperty(params.creds, params.url, params.prop)
            }
        }
        stage('Test getImageDigest') {
            steps {
                sh "echo " + params.image
                build.getImageDigest(params.image)
            }
        }
    }
}
