NODE_NAME="${JOB_BASE_NAME}-${BUILD_NUMBER}"
NODE_TMPL = "docker/ubuntu.m1.medium.yaml"
currentBuild.displayName = "#${BUILD_NUMBER}"

vm(NODE_NAME,NODE_TMPL) {
    stage("Checkout") {
        checkout poll: false,
        scm: [$class: 'GitSCM',
             branches: [[name: "master"]],
             doGenerateSubmoduleConfigurations: false,
             extensions: [[$class: 'CleanBeforeCheckout']],
             submoduleCfg: [],
             userRemoteConfigs: [[refspec: 'refs/changes/*:refs/changes/*',
             url: "https://github.com/coredns/coredns.git"]]]
    }

    stage("Build Img") {
        def build_binary = '''
            docker run --rm -v ${PWD}:/go/src/github.com/coredns/coredns \
                -w /go/src/github.com/coredns/coredns golang:1.9 make
            '''
        def stage_status = sh(returnStatus: true, script: build_binary  )
        if (stage_status != 0) {
            currentBuild.result = 'FAILED'
            slack.msg("CoreDNS: Build failed!")
        }
        sh 'docker build . -t coredns:latest'
        def TAG=sh '''
        echo `docker run coredns:latest -version` | sed -e 's/CoreDNS-//g' | awk '{print $1"-"$4}'
        '''
    }

    stage('Upload') {
        publish.artifactory('coredns:latest','coredns:latest')
        publish.artifactory('coredns:latest',"coredns:${TAG}")
    }
}
