heat_template_version: newton

description: Large instance.

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: cicd-ubuntu-16.04-server-cloudimg-amd64
      flavor: m1.large
      key_name: jenkins-slave-keypair
      networks:
        - port: { get_resource: server_port }

      user_data:
        str_replace:
          template: {get_file: bootstrap.sh}
          params:
            $message: Hello World!

  private_port:
    type: OS::Neutron::Port
    properties:
      network_id: private
      security_groups: [jenkins-security]

  routable_port:
    type: OS::Neutron::Port
    properties:
      network_id: routable
      security_groups: [jenkins-security]

outputs:
  routable_ip:
    description: The external IP associated to the server
    value: { get_attr: [routable_port, fixed_ips, 0, ip_address] }
