NODE_NAME="${JOB_BASE_NAME}-${BUILD_NUMBER}"
NODE_TMPL = "docker/ubuntu.m1.medium.yaml"
currentBuild.displayName = "${GERRIT_EVENT_TYPE}-${BUILD_NUMBER}"

vm(NODE_NAME, NODE_TMPL) {
    gerrithub.clone(GERRIT_PROJECT,GERRIT_REFSPEC)
    stage('Build'){
        sh '''export TERM='linux' DEBIAN_FRONTEND='noninteractive'
              make images IMAGE_LIST="${JOB_BASE_NAME}"    \
                          IMAGE_PREFIX="${GERRIT_PROJECT}" \
                          IMAGE_SUFFIX="${JOB_BASE_NAME}"  \
                          IMAGE_TAG="0.1.0.${GERRIT_CHANGE_NUMBER}"'''
    }
//    stage('Test'){
//        // here should be tests implemented by UCP team.
//        // but for now I just checking that maas packages are installed.
//        sh '''docker images | grep "${GERRIT_PROJECT}/${JOB_BASE_NAME}"
//              IMG_NAME="${GERRIT_PROJECT}/${JOB_BASE_NAME}:0.1.0.${GERRIT_CHANGE_NUMBER}"
//              docker run -i "${IMG_NAME}" bash -ci "dpkg -l | grep maas" '''
//    }
    stage('Publish'){
        IMG="${GERRIT_PROJECT}/${JOB_BASE_NAME}:0.1.0.${GERRIT_CHANGE_NUMBER}"
        // on patchset-created (and other non merge events) we'll push img named like:
        //Example: http://<art_path>/ucp-patchset/maas/maas-rack-controller:12345
        IMG_REMOTE="ucp-patchset/maas/${JOB_BASE_NAME}:${GERRIT_CHANGE_NUMBER}"

        if (GERRIT_EVENT_TYPE == 'change-merged'){
        // 2 images on merge (every merge will update ':latest' image)
        // http://<art_path>/ucp/maas/maas-rack-controller:0.1.0.12345
        // http://<art_path>/ucp/maas/maas-rack-controller:latest
            IMG_REMOTE="ucp/maas/${JOB_BASE_NAME}:0.1.0.${GERRIT_CHANGE_NUMBER}"
            IMG_LATEST="ucp/maas/${JOB_BASE_NAME}:latest"
            publish.artifactory(IMG,IMG_LATEST)
        }
        publish.artifactory(IMG,IMG_REMOTE)
    }
}
