NODE_NAME="${JOB_BASE_NAME}-${BUILD_NUMBER}"
NODE_TMPL = "docker/ubuntu.m1.medium.yaml"
currentBuild.displayName = "${GERRIT_EVENT_TYPE}-${BUILD_NUMBER}"

vm(NODE_NAME, NODE_TMPL) {
    gerrithub.clone(GERRIT_PROJECT,GERRIT_REFSPEC)
    stage('Build'){
        sh '''export TERM='linux' DEBIAN_FRONTEND='noninteractive'
              make images IMAGE_LIST="${JOB_BASE_NAME}"    \
                          IMAGE_PREFIX="${GERRIT_PROJECT}" \
                          IMAGE_SUFFIX="${JOB_BASE_NAME}"  \
                          IMAGE_TAG="0.1.0.${GERRIT_CHANGE_NUMBER}"'''
    }
    stage('Test'){
        // here should be tests implemented by UCP team.
        // but for now I just checking that maas packages are installed.
        sh '''docker images | grep "${GERRIT_PROJECT}/${JOB_BASE_NAME}"
              IMG_NAME="${GERRIT_PROJECT}/${JOB_BASE_NAME}:0.1.0.${GERRIT_CHANGE_NUMBER}"
              docker run -ti "${IMG_NAME}" bash -ci "dpkg -l | grep maas" '''
    }
    stage('Publish')
    {
        IMG="${GERRIT_PROJECT}/${JOB_BASE_NAME}:0.1.0.${GERRIT_CHANGE_NUMBER}"
        IMG_REMOTE="ucp/${GERRIT_PROJECT}/${JOB_BASE_NAME}:0.1.0.${GERRIT_CHANGE_NUMBER}"
        publish.artifactory(IMG,IMG_REMOTE)

        if (GERRIT_EVENT_TYPE == 'change-merged'){
            IMG_LATEST="ucp/${GERRIT_PROJECT}/${JOB_BASE_NAME}:latest"
            publish.artifactory(IMG,IMG_LATEST)
        }
    }
}
