JENKINS_VM_LAUNCH='local-vm-launch'
NODE_NAME="${JOB_BASE_NAME}-${BUILD_NUMBER}"
NODE_TMPL="resources/heat/ubuntu1804.m1.large.yaml"
artf_repo="cloud-images-local"
artf_ubuntu_repo="https://$ARTF_WEB_URL/ubuntu"

/* start of bash scripts */

def hello_world = '''
  echo "Hello world."
'''

/* end of bash scripts */

vm(NODE_NAME, NODE_TMPL) {
   stage('Setup environment'){

    sh(returnStatus: true, script: hello_world)
  }

  stage('Build images'){

    sh(returnStatus: true, script: hello_workd)
  }

  stage('Smoke Test packages'){

    sh(returnStatus: true, script: hello_world)
  }

  stage('Publish images'){

    sh(returnStatus: true, script: hello_world)
  }
}
