currentBuild.displayName = "#${BUILD_NUMBER}-${GERRIT_EVENT_TYPE}"
GIT_COMMIT=""

vm2("bootstrap.sh", "cicd-ubuntu-16.04-server-cloudimg-amd64", "m1.large", 'airship-deckhand', 'basic', false) {
    sh ('hostname')
    stage('Setup environment'){
        vm2.setproxy()
        sh 'sudo apt-get update'
        sh 'sudo apt-get install -y make curl'
    }
    stage('Install Helm'){
        git branch:"master", url:"https://github.com/openstack/openstack-helm-infra"
        sh "git checkout ${OPENSTACK_HELM_INFRA_COMMIT}"
        HELM_TOOLKIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
        sh "sed -i 's/8.8.8.8/${ARTF_IP}/g' ./tools/images/kubeadm-aio/assets/opt/playbooks/vars.yaml"
        def amap = ['kubernetes_network_default_device': 'docker0','proxy': [ 'http': "${HTTP_PROXY}", 'https': "${HTTP_PROXY}", 'noproxy': "127.0.0.1,localhost,172.17.0.1,.svc.cluster.local"] ]

        sh 'rm -rf ./tools/gate/devel/local-vars.yaml'
        writeYaml file: './tools/gate/devel/local-vars.yaml', data: amap

        sh 'make dev-deploy setup-host'
        sh 'make dev-deploy k8s'
    }

    stage('Project Checkout'){
        if("${GERRIT_EVENT_TYPE}" == "patchset-created"){
            gerrit.cloneToBranch("https://git.openstack.org/openstack/airship-deckhand", "${GERRIT_PATCHSET_REVISION}","airship-deckhand")
            dir("${WORKSPACE}/airship-deckhand"){
                gerrit.rebase()
            }
        } else {
            gerrit.cloneToBranch("https://git.openstack.org/openstack/airship-deckhand", "${DECKHAND_COMMIT}","airship-deckhand")
        }
        dir("${WORKSPACE}/airship-deckhand"){
            GIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            def chartVersion = readYaml file: "charts/deckhand/Chart.yaml"
            def chartOverride = readYaml file: "charts/deckhand/Chart.yaml", text: "version: ${GIT_COMMIT}.${HELM_TOOLKIT_COMMIT}"
            sh 'sudo rm -rf charts/deckhand/Chart.yaml'
            writeYaml file: "charts/deckhand/Chart.yaml", data: chartOverride
            sh "cat charts/deckhand/Chart.yaml"
        }
    }
    dir("${WORKSPACE}/airship-deckhand"){
        stage('Build & Package'){
            def status = sh(returnStatus: true, script: "sudo make charts")
            if (status != 0) {
                currentBuild.result = 'FAILED'
                notify.msg("Charts build failed for ${GIT_COMMIT}!")
            }else{
                notify.msg("Charts were built for ${GIT_COMMIT}")
            }
        }
        stage('Publish'){
            ARTF_REPO="airship-helm-local/airship"
            if("${GERRIT_EVENT_TYPE}" != "change-merged"){
                ARTF_REPO="${ARTF_REPO}/test"
            }

            def server = Artifactory.server 'artifactory'
            def uploadSpec = """{"files": [{"pattern":"*.tgz","target":"${ARTF_REPO}/deckhand/"}]}"""
            server.upload(uploadSpec)
            notify.msg("Chart for ${GIT_COMMIT}.${HELM_TOOLKIT_COMMIT} pushed to ${ARTF_REPO}/deckhand/")
        }
    }
}