heat_template_version: ocata

description: Generic template for launching VM from volume

parameters:
  public_net:
    type: string
    default: public
  private_net:
    type: string
    default: public
  image:
    type: string
    default: bionic-server-cloudimg-amd64
  flavor:
    type: string
    default: m1.large
  key:
    type: string
    default: jenkins-slave-keypair

resources:
  server:
    type: OS::Nova::Server
    properties:
      config_drive: true
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - port: { get_resource: server_port }
      block_device_mapping:
        - device_name: vda
          volume_id: { get_resource: cinder_volume }
          delete_on_termination: true
      user_data_format: RAW
      user_data: {get_file: cloud-config}

  cinder_volume:
    type: OS::Cinder::Volume
    properties:
      size: 300
      image: { get_param: image }

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id:
        get_param: public_net
      security_groups: [jenkins-security]

outputs:
  floating_ip:
    description: The external IP associated to the server
    value: { get_attr: [server, first_address ] }
