heat_template_version: newton

description: This template brings up a stack, setting flavor, size of VM, port & floating IP

parameters:
  public_net:
    type: string
    default: public
  private_net:
    type: string
    default: private
  image:
    type: string
    default: cicd-ubuntu-16.04-server-cloudimg-amd64
  flavor:
    type: string
    default: m1.large

conditions:
  add_routable_ip:
    not:
      equals:
        - get_param: public_net
        - ''

resources:
  server:
    type: OS::Nova::Server
    properties:
      config_drive: true
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: jenkins-slave-keypair
      networks:
        - port: { get_resource: private_port }
        - port: { get_resource: routable_port }

      user_data:
        str_replace:
          template:
            get_file: cloud-config
          params:
            $message: Hello World!

  private_port:
    type: OS::Neutron::Port
    properties:
      network_id:
        get_param: private_net
      security_groups: [jenkins-security]

  routable_port:
    type: OS::Neutron::Port
    properties:
      network_id: routable
      security_groups: [jenkins-security]

outputs:
  routable_ip:
    description: The external IP associated to the server
    value:
      if:
        - add_routable_ip
        - get_attr:
            - routable_port
            - fixed_ips
            - 0
            - ip_address
        - get_attr:
            - private_port
            - fixed_ips
            - 0
            - ip_address
