heat_template_version: newton

description: This template brings up a stack, setting flavor, size of VM, port & floating IP

parameters:
  public_net:
    type: string
    default: public
  private_net:
    type: string
    default: private
  image:
    type: string
    default: cicd-ubuntu-16.04-server-cloudimg-amd64
  flavor:
    type: string
    default: m1.large

resources:
  server:
    type: OS::Nova::Server
    properties:
      config_drive: true
      flavor: { get_param: flavor }
      key_name: jenkins-slave-keypair
      networks:
        - port: { get_resource: server_port }
      block_device_mapping:
        - device_name: vda
          volume_id: { get_resource: cinder_volume }
          delete_on_termination: true

      user_data:
        str_replace:
          template: {get_file: bootstrap.sh}
          params:
            $message: Hello World!

  cinder_volume:
    type: OS::Cinder::Volume
    properties:
      size: 300
      image: { get_param: image }

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id:
        get_param: private_net
      security_groups: [jenkins-security]

  server_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network:
        get_param: public_net
      port_id: { get_resource: server_port }

outputs:
  floating_ip:
    description: The external IP associated to the server
    value: { get_attr: [server_floating_ip, floating_ip_address] }

