heat_template_version: newton

description: This template brings up a stack, setting flavor, size of VM, port & floating IP

parameters:
  public_net:
    type: string
    default: public
  private_net:
    type: string
    default: private
  image:
    type: string
    default: cicd-ubuntu-16.04-server-cloudimg-amd64
  flavor:
    type: string
    default: m1.large
  init_script:
    type: string
    default: bootstrap.sh

conditions:
    add_floatingip:
      not:
        equals:
          - get_param: public_net
          - null

resources:
  server:
    type: OS::Nova::Server
    properties:
      config_drive: true
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: jenkins-slave-keypair
      networks:
        - port: { get_resource: server_port }

      user_data:
        str_replace:
          template:
            get_file: { get_param: init_script }
          params:
            $message: Hello World!

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id:
        get_param: private_net
      security_groups: [jenkins-security]

  server_floating_ip:
    condition: add_floatingip
    type: OS::Neutron::FloatingIP
    properties:
      floating_network:
        get_param: public_net
      port_id: { get_resource: server_port }

outputs:
  floating_ip:
    description: The external IP associated to the server
    value:
      if:
        - add_floatingip
        - get_attr:
            - server_floating_ip
            - floating_ip_address
        - get_attr:
            - server
            - first_address
