JENKINS_VM_LAUNCH='local-vm-launch'
NODE_NAME="shipyard-${BUILD_NUMBER}"
NODE_TMPL="integration/genesis-single.yaml"

SHIPYARD_VERSION = "0.1.0-${GERRIT_CHANGE_NUMBER}"
SHIPYARD_PS = "${GERRIT_CHANGE_NUMBER}.${GERRIT_PATCHSET_NUMBER}"
ARTF_URL = env.ARTF_DOCKER_URL
SHIPYARD_IMAGE_PS = "${ARTF_URL}/ucp-patchset/shipyard:${SHIPYARD_PS}"
SHIPYARD_IMAGE = "${ARTF_URL}/ucp/shipyard:${SHIPYARD_VERSION}"
SHIPYARD_IMAGE_LATEST = "${ARTF_URL}/ucp/shipyard:latest"

vm(NODE_NAME, NODE_TMPL) {
    gerrithub.clone("att-comdev/shipyard", GERRIT_REFSPEC)
    sh 'sudo apt-get install make'
    stage('Checkout'){
        if (GERRIT_EVENT_TYPE != 'change-merged') {
            SHIPYARD_IMAGE = SHIPYARD_IMAGE_PS
        }
        currentBuild.displayName = "#${BUILD_NUMBER} ${GERRIT_EVENT_TYPE}"
    }
    stage('Docker Build') {
        timeout(20){
            node(NODE_NAME){
                dir("${WORKSPACE}/images/att-comdev/shipyard/shipyard"){
                   sh  "sudo make build_shipyard IMAGE_TAG='${BUILD_NUMBER}'"
                   sh  "sudo docker tag attcomdev/shipyard:${BUILD_NUMBER} ${SHIPYARD_IMAGE}"
                }
            }
        }
    }

    stage('Docker Run') {
        timeout(20){
           node( NODE_NAME){
              dir("${WORKSPACE}/images/att-comdev/shipyard/shipyard"){
                  sh  "sudo make run_shipyard IMAGE_TAG='${BUILD_NUMBER}'"
              }
           }
        }
    }

    stage('Validate Container') {
        sh 'sudo docker ps'
    }

    stage('Publish'){
        withCredentials([usernamePassword(credentialsId: 'jenkins-artifactory',
                usernameVariable: 'ARTIFACTORY_USER',
                passwordVariable: 'ARTIFACTORY_PASSWORD')]) {

            opts = '-u $ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD'

            sh "sudo docker login ${opts} ${ARTF_URL}"
            sh "sudo docker push ${SHIPYARD_IMAGE}"

            if (GERRIT_EVENT_TYPE == 'change-merged') {
                sh "sudo docker tag ${SHIPYARD_IMAGE} ${SHIPYARD_IMAGE_LATEST}"
                sh "sudo docker push ${SHIPYARD_IMAGE_LATEST}"
            }
        }
        withCredentials([usernamePassword(credentialsId: 'jenkins-quay',
                usernameVariable: 'QUAY_USER',
                passwordVariable: 'QUAY_PASSWORD')]) {

            opts = '-u $QUAY_USER -p $QUAY_PASSWORD'

            sh "sudo docker login ${opts} quay.io"
            sh "sudo docker tag ${SHIPYARD_IMAGE} ${QUAY_URL}/attcomdev/shipyard:${SHIPYARD_PS}"
            
            sh "sudo docker push ${QUAY_URL}/attcomdev/shipyard:${SHIPYARD_PS}"

            if (GERRIT_EVENT_TYPE == 'change-merged') {
                sh "sudo docker tag ${QUAY_URL}/attcomdev/shipyard:${SHIPYARD_PS} ${QUAY_URL}/attcomdev/shipyard:latest"
                sh "sudo docker push ${QUAY_URL}/attcomdev/shipyard:latest"
            }
        }
    }
}