
def fip = vm(initScript: NODE_DATA,
             image: NODE_IMAGE,
             flavor: NODE_FLAVOR,
             nodePostfix: NODE_POSTFIX,
             doNotDeleteNode: true) {

  sh ('hostname')
  sh("echo ${SSH_KEY} >> /home/ubuntu/.ssh/authorized_keys")
}

currentBuild.displayName = "#${BUILD_NUMBER} VM ${NODE_POSTFIX} ${fip}"
print "Access VM on Floating IP => ubuntu@${fip}"
