NODE_NAME="calico-${JOB_BASE_NAME}-${BUILD_NUMBER}"
NODE_TMPL = "docker/ubuntu.m1.medium.yaml"
currentBuild.displayName = "#${BUILD_NUMBER}"
PROJECT_URL = "https://github.com/projectcalico/${JOB_REPO}.git"

vm(NODE_NAME,NODE_TMPL) {
    stage("Checkout"){
        checkout poll: false,
        scm: [$class: 'GitSCM',
             branches: [[name: "master"]],
             doGenerateSubmoduleConfigurations: false,
             extensions: [[$class: 'CleanBeforeCheckout']],
             submoduleCfg: [],
             userRemoteConfigs: [[refspec: 'refs/changes/*:refs/changes/*',
             url: PROJECT_URL ]]]
    }
    stage("Build Image"){
        dir(JOB_REPO){
            if(JOB_BASE_NAME == 'node') {
                dir("calico_node"){
                    sh "make calico/node GOBGPD_VER=v0.2.2 LIBNETWORK_PLUGIN_VER=v1.1.2"
                }
            } else {
                sh "make docker-image"
            }
        }
    }
    stage("publish"){
        publish.artifactory("calico/${JOB_BASE_NAME}:latest","calico/${JOB_BASE_NAME}:latest")
    }
}
