# Copyright 2018 The OpenStack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# openstack stack create --wait -t osh-node-flavor.yaml osh-node-flavor
heat_template_version: 2016-10-14

resources:
  flavor:
    type: OS::Nova::Flavor
    properties:
      name: osh-node-flavor
      disk: 64
      ram: 32768
      vcpus: 8
