
NODE_NAME="osh-single-${BUILD_NUMBER}"
NODE_TMPL = "promenade/osh-single.yaml"


vm(NODE_NAME, NODE_TMPL) {

    gerrithub.clone(GERRIT_PROJECT, GERRIT_REFSPEC)

    def scripts = ['00-install-packages.sh',
                   '01-deploy-k8s.sh',
                   '02-setup-client.sh',
                   '03-ingress.sh',
                   '04-ceph.sh',
                   '05-ceph-ns-activate.sh',
                   '06-mariadb.sh',
                   '07-rabbitmq.sh',
                   '08-memcached.sh']

    scripts.each {
        timeout (10) {
            stage("OSH (${it})") {
                sh "tools/deployment/developer/${it}"
            }
        }
    }
}

