
NODE_NAME="osh-single-${BUILD_NUMBER}"
NODE_TMPL = "promenade/osh-single.yaml"


vm(NODE_NAME, NODE_TMPL) {

    checkout poll: false,
    scm: [$class: 'GitSCM',
        branches: [[name: '$GERRIT_REFSPEC']],
        doGenerateSubmoduleConfigurations: false,
        extensions: [[$class: 'RelativeTargetDirectory',
            relativeTargetDir: 'openstack-helm']],
        submoduleCfg: [],
        userRemoteConfigs: [[refspec: 'refs/changes/*:refs/changes/*',
        url: "https://git.openstack.org/openstack/openstack-helm" ]]]


    checkout([$class: 'GitSCM',
        branches: [[name: '*/master']],
        doGenerateSubmoduleConfigurations: false,
        extensions: [[$class: 'RelativeTargetDirectory',
            relativeTargetDir: 'openstack-helm-infra']],
        submoduleCfg: [],
        userRemoteConfigs:
            [[url: 'https://git.openstack.org/openstack/openstack-helm-infra']]])


    def scripts = ['00-install-packages.sh',
                   '01-deploy-k8s.sh',
                   '02-setup-client.sh',
                   '03-ingress.sh',
                   '04-ceph.sh',
                   '05-ceph-ns-activate.sh',
                   '06-mariadb.sh',
                   '07-rabbitmq.sh',
                   '08-memcached.sh',
                   '09-keystone.sh']

    scripts.each {
        timeout (14) {
            stage("OSH (${it})") {
                dir ('openstack-helm') {
                    sh "tools/deployment/developer/${it}"
                }
            }
        }
    }
}

