// pipeline for virtual multi-node gate

ARTF_BASE = "cicd/logs/${JOB_NAME}/${BUILD_ID}"

REPO_URL = 'https://review.opendev.org/airship/in-a-bottle'
REPO_HOME = '/root/deploy/in-a-bottle'

publicNet = 'public'
if (env.AIRSHIP_VM_PUBLIC_NET) {
    publicNet = env.AIRSHIP_VM_PUBLIC_NET
}

image = 'ubuntu-18.04'
if (env.AIRSHIP_MULTINODE_VM_IMAGE) {
    image = env.AIRSHIP_MULTINODE_VM_IMAGE
}

vm(flavor: 'airship.seaworthy',
        image: image,
        artifactoryLogs: true,
        doNotDeleteNode: false,
        timeout: 300,
        publicNet: publicNet) {

    stage('Checkout'){

        sh 'sudo mkdir /root/deploy'
        sh 'sudo setfacl -m u:ubuntu:rwx /root/deploy'
        sh 'sudo setfacl -m u:ubuntu:rwx /root'

        // fixme: this should be fixed in gate setup scripts
        sh 'sudo groupadd libvirtd'
        sh 'sudo useradd virtmgr'
        sh 'sudo usermod -a -G libvirtd virtmgr'

        gerrit.cloneToBranch(REPO_URL, GERRIT_PATCHSET_REVISION, REPO_HOME)

        if(GERRIT_EVENT_TYPE != 'change-merged') {
            dir(REPO_HOME) {
                gerrit.rebase()
            }
        }
        currentBuild.displayName = "#${BUILD_NUMBER} ${GERRIT_EVENT_TYPE}"
    }

    stage('Setup Gate') {
        dir("${REPO_HOME}/tools/multi_nodes_gate"){
            timeout(20){
                ansiColor('xterm') {
                    sh 'sudo ./setup_gate.sh'
                }
            }
        }
    }

    stage('Run Airship') {
        dir("${REPO_HOME}/tools/multi_nodes_gate"){
            timeout(240){
                ansiColor('xterm') {

                    // use Westmere for nested VMs
                    def opts = ["VIRSH_CPU_OPTS=Westmere"]

                    withEnv(opts) {
                        sh 'sudo -E ./gate.sh'
                    }
                }
            }
        }
    }
}

