import com.att.nccicd.config.conf as ncconfig
ncconf = new ncconfig(env).CONF

IMAGE_PREFIX="openstack"
IMAGE_TAG="${IMAGE_PREFIX}/${JOB_BASE_NAME}"
IMAGE_TEST="${IMAGE_PREFIX}/test/${JOB_BASE_NAME}:${GERRIT_EVENT_TYPE}"
IMAGE_LATEST="${IMAGE_PREFIX}/${JOB_BASE_NAME}:latest"
IMAGE_MERGE="${IMAGE_PREFIX}/${JOB_BASE_NAME}:${GERRIT_PATCHSET_REVISION}.${BUILD_TIMESTAMP}"
UPSTREAM_URL="https://review.opendev.org/x/"
RANGER_USER=ncconf.RANGER_USER
RANGER_AGENT_USER=ncconf.RANGER_AGENT_USER
currentBuild.displayName="Build #${BUILD_NUMBER} ${JOB_BASE_NAME} ${GERRIT_BRANCH} ${GERRIT_EVENT_TYPE}"
def label="worker-${UUID.randomUUID().toString()}"

try {
    podTemplate(label: label,yaml: """
               apiVersion: v1
               kind: Pod
               spec:
                 securityContext:
                   runAsUser: 0
                 nodeSelector:
                   jenkins-node: enabled
               """, containers: [
                   containerTemplate(name: "ubuntu",
                                     image: "${ARTF_DOCKER_URL}/ubuntu_copy/18.04/nc-ubuntu-18.04@sha256:a08437dd42b2d095cef653d485414fe351401c55b480f16908d5911e4ba75c0f",
                                     command: "cat",
                                     ttyEnabled: true)],
                   volumes: [hostPathVolume(hostPath: '/var/run/dindproxy/docker.sock', mountPath: '/var/run/docker.sock')]) {
        node(label){
            container("ubuntu"){
                stage('Checkout'){
                    sh 'apt-get -y install make docker.io'
                    if (GERRIT_EVENT_TYPE == 'manual') {
                        gerrit.clone("${UPSTREAM_URL}${JOB_BASE_NAME}", GERRIT_PATCHSET_REVISION, "")
                    }
                    else {
                        gerrit.cloneToBranch("${UPSTREAM_URL}${JOB_BASE_NAME}","${IMAGE_TAG}","")
                    }
                    if (GERRIT_EVENT_TYPE == 'change-merged') {
                        sh '''git config user.email "airship.jenkins@gmail.com"
                            git config user.name "Jenkins"
                            git pull --rebase origin ${GERRIT_BRANCH}'''
                    }
                }

                stage('Docker Build') {
                    timeout(20){
                            sh "make images IMAGE_NAME=${JOB_BASE_NAME} USE_PROXY=true PROXY=${HTTP_PROXY} IMAGE_PREFIX=${IMAGE_PREFIX} DOCKER_REGISTRY=${ARTF_DOCKER_URL} LABEL='org.label-schema.vcs-ref=${GERRIT_PATCHSET_REVISION} --label org.label-schema.vcs-url=${GERRIT_CHANGE_URL} --label org.label-schema.version=0.1.0 --label org.label-schema.branch=${GERRIT_BRANCH}' IMAGE_TAG=${GERRIT_PATCHSET_REVISION} RANGER_USER=${RANGER_USER} RANGER_AGENT_USER=${RANGER_AGENT_USER}"
                    }
                }
                stage('Docker Run') {
                    timeout(20){
                       IMAGE = "${ARTF_DOCKER_URL}/${IMAGE_LATEST}"
                       sh "docker run ${IMAGE}"
                    }
                }

                stage('Publish'){
                    if (${GERRIT_EVENT_TYPE} == 'change-merged') {
                        publish.artifactory ("${UPSTREAM_URL}${JOB_BASE_NAME}${GERRIT_CHANGE_NUMBER}", "${IMAGE_MERGE}", useSudo=false)
                        publish.artifactory ("${UPSTREAM_URL}${JOB_BASE_NAME}${GERRIT_CHANGE_NUMBER}", "${IMAGE_LATEST}", useSudo=false)
                    }
                    else {
                        publish.artifactory ("${UPSTREAM_URL}${JOB_BASE_NAME}", "${IMAGE_TEST}", useSudo=false)
                        publish.artifactory ("${UPSTREAM_URL}${JOB_BASE_NAME}", "${IMAGE_LATEST}", useSudo=false)
                    }
                }
            }
        }
    }
// catch both errors and exceptions
} catch (Throwable err) {
    currentBuild.result = 'FAILURE'
    if (env.GERRIT_EVENT_TYPE == 'change-merged') {
        email.sendMail(recipientProviders: [developers(), requestor()],
                       to: env.EMAIL_LIST)
    }
    throw err
}
