JENKINS_VM_LAUNCH = 'local-vm-launch'
NODE_NAME="openstack-helm-${env.BUILD_NUMBER}"
NODE_TMPL = "openstack-helm/openstack-helm.yaml"
ARTF_URL = env.ARTF_WEB_URL
OSH_VERSION = "0.1.0.${env.BUILD_NUMBER}"
OSH_PS_ARTF_REPO = "openstack-patchset/openstack-helm/"+OSH_VERSION
OSH_ARTF_REPO = "openstack/openstack-helm/"+OSH_VERSION
def funcs

try{
    stage('Create Jenkins Node'){
        node(JENKINS_VM_LAUNCH) {
            gerrit.cloneUpstream(repo: 'att-comdev/cicd', refspec: 'master', targetDirectory: '.')

            funcs = load "${WORKSPACE}/integration/funcs.groovy"
            funcs.jenkins_slave_launch(NODE_NAME, "${env.HOME}/${NODE_TMPL}")
        }
    }
    stage('Nodes Wait'){
        timeout (10) {
            node (NODE_NAME) {
                echo "Verifying that Jenkins node comes up."
            }
        }
    }
    node(NODE_NAME) {
        ansiColor('xterm') {
            stage('Checkout') {
                gerrit.cloneRepository url: 'https://git.openstack.org/openstack/openstack-helm',
                                        refspec: GERRIT_REFSPEC,
                                        targetDirectory: '.'
            }
            stage('Kubeadm-AIO') {
                try {
                    timeout(45) {
                        withEnv(["INTEGRATION=aio",
                                 "INTEGRATION_TYPE=basic",
                                  "POD_START_TIMEOUT=720"]) {
                            sh "./tools/gate/setup_gate.sh"
                        }
                    }
                    def server = Artifactory.server 'artifactory'
                    if ( "${GERRIT_EVENT_TYPE}" == 'change-merged' || "$GERRIT_EVENT_TYPE" =='change-merged' ){
                        withCredentials([usernamePassword(credentialsId: 'jenkins-artifactory',
                            usernameVariable: 'ARTIFACTORY_USER',
                            passwordVariable: 'ARTIFACTORY_PASSWORD')]) {
                            def uploadSpec = """{"files": [{"pattern": "*-0.1.0.tgz",
                                                            "target": "$OSH_ARTF_REPO/"
                                                }]}"""
                            server.upload(uploadSpec)
                        }
                    } else {
                        withCredentials([usernamePassword(credentialsId: 'jenkins-artifactory',
                            usernameVariable: 'ARTIFACTORY_USER',
                            passwordVariable: 'ARTIFACTORY_PASSWORD')]) {
                            def uploadSpec = """{"files": [{"pattern": "*-0.1.0.tgz",
                                                            "target": "$OSH_PS_ARTF_REPO/"
                                                }]}"""
                            server.upload(uploadSpec)
                        }
                    }
                } finally {
                    stage('Publish Logs'){
                        node(NODE_NAME){
                            try {
                                sh 'mkdir -p logs'
                                sh 'tar -cf logs-basic-$BUILD_NUMBER.tgz logs'
                                nexusArtifactUploader artifacts: [[ artifactId: 'org.openstack.helm',
                                                                    classifier: '',
                                                                    file: 'logs-basic-$BUILD_NUMBER.tgz',
                                                                    type: 'x-gtar']],
                                                    credentialsId: 'nexus3',
                                                    groupId: 'openstack-helm',
                                                    nexusUrl: '$NEXUS3_URL',
                                                    nexusVersion: 'nexus3',
                                                    protocol: 'http',
                                                    repository: 'att-comdev-jenkins-logs',
                                                    version: '$BUILD_NUMBER'
                            } catch (Exception e) {
                            // ignore artifactory errors for now
                            }
                        }
                    }
                }
            }
        }
    }
} finally {
    stage('Delete Jenkins Node'){
       node(JENKINS_VM_LAUNCH) {
           funcs.jenkins_slave_destroy(NODE_NAME)
        }
    }
}