VM_LAUNCH_NODE = 'local-vm-launch'
SLAVE_NODE= "functions-test-node"
NODE_TMPL = "docker/ubuntu.m1.medium.yaml"
ARTF_URL = env.ARTF_DOCKER_URL

def funcs
def testf

try{
    stage('Create Slave Node'){
        node(VM_LAUNCH_NODE) {
            //I don't want to clone repo every time:
            sh '''#!/bin/bash -xe

                  if [ ! -d cicd ]; then
                    git clone https://review.gerrithub.io/att-comdev/cicd
                  fi
                    cd cicd
                    git fetch https://review.gerrithub.io/att-comdev/cicd ${GERRIT_REFSPEC}
                    git checkout FETCH_HEAD
            '''
            funcs = load "cicd/common/funcs.groovy"
            funcs.jenkins_slave_launch(SLAVE_NODE, "${env.HOME}/${NODE_TMPL}")
            // we'll move working functions to funcs.groovy after testing:
            testf = load "cicd/common/test_functions.groovy"
            testf.Notify('#test-jenkins', "Hello from test job! \nTest param1: ${env.TEST_PARAM1}")

        }
    }
    stage('Wait for Node'){
        timeout (10) {
            node (SLAVE_NODE) {
                echo "It's up."
            }
        }
    }

    node(SLAVE_NODE) {
        stage('Checkout and Load') {
            checkout poll: false,
            scm: [$class: 'GitSCM',
                branches: [[name: "${GERRIT_REFSPEC}"]],
                doGenerateSubmoduleConfigurations: false,
                extensions: [[$class: 'CleanBeforeCheckout']],
                submoduleCfg: [],
                userRemoteConfigs: [[refspec: 'refs/changes/*:refs/changes/*',
                url: "https://review.gerrithub.io/att-comdev/cicd"]]]

            sh "ls -lah * && git log ||:"

            // we'll move working functions to funcs.groovy after testing:
            testf = load "common/test_functions.groovy"
        }

        stage('Testing functions'){

            testf.Notify('#test-jenkins', "Hello from test job! \nTest param2: ${env.TEST_PARAM2}")

        }
    }

} finally {

    stage('Remove Slave'){
       node(VM_LAUNCH_NODE) {
           funcs.jenkins_slave_destroy(SLAVE_NODE)
        }
    }
}
