currentBuild.displayName = "#${BUILD_NUMBER}-${GERRIT_EVENT_TYPE}"
PROMENADE_COMMIT=""

vm(flavor: "m1.large"){
    sh ('hostname')
    stage('Setup environment'){
        vm2.setproxy()
    }

    stage('Infra Helm Checkout'){

        if ("${GERRIT_PROJECT}" == "${INFRA_PROJECT}" && "${GERRIT_EVENT_TYPE}" == "change-merged"){
            sh 'echo Openstack-helm-infra ${GERRIT_NEWREV} just merged'
            gerrit.cloneToBranch("https://git.openstack.org/${INFRA_PROJECT}", "${GERRIT_NEWREV}","openstack-helm-infra")
            dir("${WORKSPACE}/openstack-helm-infra"){
                HELM_TOOLKIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            }
        }else {
            sh 'mkdir -p openstack-helm-infra'
            dir("${WORKSPACE}/openstack-helm-infra") {
                git branch: "master", url: "https://git.openstack.org/${INFRA_PROJECT}"
                sh "git checkout ${OPENSTACK_HELM_INFRA_COMMIT}"
                HELM_TOOLKIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            }
        }

    }
    stage('Promenade Checkout'){
        if ("${GERRIT_PROJECT}" == "${PROMENADE_PROJECT}" && "${GERRIT_EVENT_TYPE}" != "change-merged") {
            sh 'echo Promenade commit SHA: ${GERRIT_PATCHSET_REVISION}'
            gerrit.cloneToBranch("https://git.openstack.org/${PROMENADE_PROJECT}", "${GERRIT_PATCHSET_REVISION}", "${JOB_BASE_NAME}")
        }else if("${GERRIT_PROJECT}" == "${PROMENADE_PROJECT}" && "${GERRIT_EVENT_TYPE}" == "change-merged"){
            sh 'echo Promenade commit SHA: ${GERRIT_NEWREV}'
            gerrit.cloneToBranch("https://git.openstack.org/${PROMENADE_PROJECT}", "${GERRIT_NEWREV}", "${JOB_BASE_NAME}")
        }else{
            sh 'mkdir -p ${JOB_BASE_NAME}'
            dir("${WORKSPACE}/${JOB_BASE_NAME}") {
                git "https://git.openstack.org/${PROMENADE_PROJECT}"
                sh "git checkout master"
            }
        }
        dir("${WORKSPACE}/${JOB_BASE_NAME}"){
            PROMENADE_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            sh "echo Chart version: ${PROMENADE_COMMIT}.${HELM_TOOLKIT_COMMIT}"
            sh "sed -i 's/cd openstack-helm-infra/& \\&\\& git reset --hard ${HELM_TOOLKIT_COMMIT}/' ./tools/helm_tk.sh"
            sh "cat ./tools/helm_tk.sh"
        }
    }
    dir("${WORKSPACE}/${JOB_BASE_NAME}"){
        stage('Build & Package'){
            sh 'sudo apt update'
            sh 'sudo apt-get install -y make'
            def status = sh(returnStatus: true, script: "sudo make charts")
            if (status != 0) {
                currentBuild.result = 'FAILED'
                notify.msg("Charts build failed for Promenade SHA: ${PROMENADE_COMMIT} " +
                        "and Helm toolkit SHA: ${HELM_TOOLKIT_COMMIT}")
            }else{
                notify.msg("Charts were built for Promenade SHA: ${PROMENADE_COMMIT} " +
                        "and Helm toolkit SHA: ${HELM_TOOLKIT_COMMIT}")
            }
        }

        stage('Rename tarballs') {

            sh("rename s/0.1.0/${PROMENADE_COMMIT}.${HELM_TOOLKIT_COMMIT}/g charts/*")
        }
        stage('Publish'){
            ARTF_REPO="airship-helm-local/airship"
            if("${GERRIT_EVENT_TYPE}" != "change-merged"){
                ARTF_REPO="${ARTF_REPO}/test"
            }

            publish.putArtifacts("*${PROMENADE_COMMIT}.${HELM_TOOLKIT_COMMIT}.tgz", "${ARTF_REPO}/promenade/")
            notify.msg("charts for ${PROMENADE_COMMIT}.${HELM_TOOLKIT_COMMIT} pushed to ${ARTF_REPO}/promenade")

        }
    }
}

