currentBuild.displayName = "#${BUILD_NUMBER}-${GERRIT_EVENT_TYPE}"
PROMENADE_COMMIT=""
def charts_list = []

vm(flavor: "m1.large"){
    sh ('hostname')
    stage('Setup environment'){
        vm2.setproxy()
    }

    stage('Infra Helm Checkout'){

        if ("${GERRIT_PROJECT}" == "${INFRA_PROJECT}" && "${GERRIT_EVENT_TYPE}" == "change-merged"){
            sh 'echo Openstack-helm-infra ${GERRIT_PATCHSET_REVISION} just merged'
            gerrit.cloneToBranch("https://git.openstack.org/${INFRA_PROJECT}", "${GERRIT_PATCHSET_REVISION}","openstack-helm-infra")
            dir("${WORKSPACE}/openstack-helm-infra"){
                HELM_TOOLKIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            }
        }else {
            sh 'mkdir -p openstack-helm-infra'
            dir("${WORKSPACE}/openstack-helm-infra") {
                git branch: "master", url: "https://git.openstack.org/${INFRA_PROJECT}"
                sh "git checkout ${OPENSTACK_HELM_INFRA_COMMIT}"
                HELM_TOOLKIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            }
        }

    }
    stage('Promenade Checkout'){
        if ("${GERRIT_PROJECT}" == "${PROMENADE_PROJECT}") {
            sh 'echo Promenade commit SHA: ${GERRIT_PATCHSET_REVISION}'
            gerrit.cloneToBranch("https://git.openstack.org/${PROMENADE_PROJECT}", "${GERRIT_PATCHSET_REVISION}", "${JOB_BASE_NAME}")
        }else{
            sh 'mkdir -p ${JOB_BASE_NAME}'
            dir("${WORKSPACE}/${JOB_BASE_NAME}") {
                git "https://git.openstack.org/${PROMENADE_PROJECT}"
                sh "git checkout master"
            }
        }
        dir("${WORKSPACE}/${JOB_BASE_NAME}"){
            PROMENADE_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            sh "echo Chart version: ${PROMENADE_COMMIT}.${HELM_TOOLKIT_COMMIT}"
            sh "sed -i 's/cd openstack-helm-infra/cd openstack-helm-infra && git reset --hard ${HELM_TOOLKIT_COMMIT}/g' ./tools/helm_tk.sh"
            charts_list = sh returnStdout: true, script: 'ls -d charts/*/ | sed "s,/$,," | sed "s,charts/,,"'
            for (chart in charts_list) {
                def chartOverride = readYaml file: "charts/${chart}/Chart.yaml", text: "version: ${PROMENADE_COMMIT}.${HELM_TOOLKIT_COMMIT}"
                sh 'sudo rm -rf charts/${chart}/Chart.yaml'
                writeYaml file: "charts/${chart}/Chart.yaml", data: chartOverride
                sh "cat charts/${chart}/Chart.yaml"
            }
        }
    }
    dir("${WORKSPACE}/${JOB_BASE_NAME}"){
        stage('Build & Package'){
            sh 'sudo apt-get install -y make'
            def status = sh(returnStatus: true, script: "sudo make charts")
            if (status != 0) {
                currentBuild.result = 'FAILED'
                notify.msg("Charts build failed for Promenade SHA: ${PROMENADE_COMMIT} " +
                        "and Helm toolkit SHA: ${HELM_TOOLKIT_COMMIT}")
            }else{
                notify.msg("Charts were built for Promenade SHA: ${PROMENADE_COMMIT} " +
                        "and Helm toolkit SHA: ${HELM_TOOLKIT_COMMIT}")
            }
        }
        stage('Publish'){
            ARTF_REPO="airship-helm-local/airship"
            if("${GERRIT_EVENT_TYPE}" != "change-merged"){
                ARTF_REPO="${ARTF_REPO}/test"
            }
            for (chart in charts_list) {
                publish.putArtifacts("${chart}*.tgz", "${ARTF_REPO}/${chart}/")
                notify.msg("${chart} chart for ${PROMENADE_COMMIT}.${HELM_TOOLKIT_COMMIT} pushed to ${ARTF_REPO}/${chart}")
            }
        }
    }
}

