currentBuild.displayName = "#${BUILD_NUMBER}-${GERRIT_EVENT_TYPE}"
MAAS_COMMIT=""

vm(flavor: "m1.large"){
    sh ('hostname')
    stage('Setup environment'){
        vm2.setproxy()
    }

    stage('Infra Helm Checkout'){

        if ("${GERRIT_PROJECT}" == "${INFRA_PROJECT}" && "${GERRIT_EVENT_TYPE}" == "change-merged"){
            sh 'echo Openstack-helm-infra ${GERRIT_NEWREV} just merged'
            gerrit.cloneToBranch("https://review.opendev.org/${INFRA_PROJECT}", "${GERRIT_NEWREV}","openstack-helm-infra")
            dir("${WORKSPACE}/openstack-helm-infra"){
                HELM_TOOLKIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            }
        }else {
            sh 'mkdir -p openstack-helm-infra'
            dir("${WORKSPACE}/openstack-helm-infra") {
                git branch: "master", url: "https://review.opendev.org/${INFRA_PROJECT}"
                sh "git checkout ${OPENSTACK_HELM_INFRA_COMMIT}"
                HELM_TOOLKIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            }
        }
    }
    stage('Maas Checkout'){
        if ("${GERRIT_PROJECT}" == "${MAAS_PROJECT}" && "${GERRIT_EVENT_TYPE}" != "change-merged") {
            sh 'echo Maas commit SHA: ${GERRIT_PATCHSET_REVISION}'
            gerrit.cloneToBranch("https://review.opendev.org/${MAAS_PROJECT}", "${GERRIT_PATCHSET_REVISION}", "${JOB_BASE_NAME}")
        }else if ("${GERRIT_PROJECT}" == "${MAAS_PROJECT}" && "${GERRIT_EVENT_TYPE}" == "change-merged"){
            sh 'echo Maas commit SHA: ${GERRIT_NEWREV}'
            gerrit.cloneToBranch("https://review.opendev.org/${MAAS_PROJECT}", "${GERRIT_NEWREV}", "${JOB_BASE_NAME}")
        }else{
            sh 'mkdir -p ${JOB_BASE_NAME}'
            dir("${WORKSPACE}/${JOB_BASE_NAME}") {
                git "https://review.opendev.org/${MAAS_PROJECT}"
                sh "git checkout master"
            }
        }
        dir("${WORKSPACE}/${JOB_BASE_NAME}"){
            MAAS_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            sh "echo Chart version: ${MAAS_COMMIT}.${HELM_TOOLKIT_COMMIT}"
            sh "sed -i 's/--client-only/& --skip-refresh/' ./tools/helm_tk.sh"
            sh "cat ./tools/helm_tk.sh"
        }
    }
    dir("${WORKSPACE}/${JOB_BASE_NAME}"){
        stage('Build & Package'){
            sh 'sudo apt update'
            sh 'sudo apt-get install -y make'
            def status = sh(returnStatus: true, script: "sudo make charts HTK_COMMIT=${HELM_TOOLKIT_COMMIT}")
            if (status != 0) {
                currentBuild.result = 'FAILED'
                notify.msg("Charts build failed for Maas SHA: ${MAAS_COMMIT} " +
                        "and Helm toolkit SHA: ${HELM_TOOLKIT_COMMIT}")
            }else{
                notify.msg("Charts were built for Maas SHA: ${MAAS_COMMIT} " +
                        "and Helm toolkit SHA: ${HELM_TOOLKIT_COMMIT}")
            }
        }
        stage('Rename tarballs') {

            sh("rename s/0.1.0/${MAAS_COMMIT}.${HELM_TOOLKIT_COMMIT}/g ./*")
        }
        stage('Publish'){
            ARTF_REPO="airship-helm-local/airship"
            if("${GERRIT_EVENT_TYPE}" != "change-merged"){
                ARTF_REPO="${ARTF_REPO}/test"
            }
            publish.putArtifacts("maas*.tgz", "${ARTF_REPO}/maas/")
            notify.msg("Chart for ${MAAS_COMMIT}.${HELM_TOOLKIT_COMMIT} pushed to ${ARTF_REPO}/maas")
        }
    }
}
