import com.att.nccicd.config.conf as config
conf = new config(env).CONF

IMAGE_TAG = "${GERRIT_PATCHSET_REVISION}"
DOCKER_REGISTRY = "${ARTF_DOCKER_URL}"
IMAGE_PREFIX = "openstack-helm-images"
IMAGE_LATEST = "${IMAGE_PREFIX}/${JOB_BASE_NAME}:latest"
VERSION = 1.0
HELM_IMAGES_URL = "https://review.opendev.org/openstack/openstack-helm-images"
HELM_IMAGES_HOME = ""
BUILD_ARGS = []
EXTRA_BUILD_ARGS = []
BASE_IMAGE = conf.UBUNTU_BIONIC_BASE_IMAGE
SUFFIX = "ubuntu_bionic"

if ("${JOB_BASE_NAME}" == 'calicoctl-utility') {
    BASE_IMAGE = "calico/ctl:${CALICOCTL_VERSION}"
    SUFFIX = "alpine"
    BUILD_ARGS += [
        "--build-arg CALICOCTL_VERSION=${CALICOCTL_VERSION}",]
    EXTRA_BUILD_ARGS += [
        "--label calicoctl.version='${CALICOCTL_VERSION}'",]
}

if (JOB_BASE_NAME.contains('ceph-')) {
    BUILD_ARGS += [
        "--build-arg CEPH_RELEASE=${conf.CEPH_RELEASE['release']}",
        "--build-arg CEPH_RELEASE_TAG=${conf.CEPH_RELEASE['tag']}",
        "--build-arg CEPH_REPO=${conf.CEPH_REPO['repo']}",
        "--build-arg CEPH_KEY=${conf.CEPH_REPO['key']}",]
}

if ("${JOB_BASE_NAME}" == 'elasticsearch-s3') {
    SUFFIX = "7_1_0"
}

if ("${JOB_BASE_NAME}" == 'fluentd') {
    SUFFIX = "debian"
}

currentBuild.displayName = "#${BUILD_NUMBER} ${GERRIT_EVENT_TYPE}"
if(env.GERRIT_NEWREV){
    echo ("${GERRIT_NEWREV} is being used to override refspec: ${GERRIT_REFSPEC}")
    IMAGE_TAG = env.GERRIT_NEWREV
}

BUILD_ARGS += [
    "--build-arg FROM=${BASE_IMAGE}",
    "--build-arg http_proxy=${HTTP_PROXY}",
    "--build-arg https_proxy=${HTTPS_PROXY}",
    "--build-arg NO_PROXY=${NO_PROXY}",
    "--build-arg no_proxy=${NO_PROXY}",
]

EXTRA_BUILD_ARGS += [
    "--label org.opencontainers.image.revision=${IMAGE_TAG}",
    "--label org.opencontainers.image.source=${GERRIT_CHANGE_URL}",
    "--label org.opencontainers.image.project=${GERRIT_PROJECT}",
    "--label org.opencontainers.image.event=${GERRIT_EVENT_TYPE}",
    "--build-arg DOCKER_REGISTRY=${DOCKER_REGISTRY}",
]

def label = "worker-${UUID.randomUUID().toString()}"
try {
    podTemplate(label: label,
                yaml: cicd_helper.podExecutorConfig(conf.JNLP_IMAGE, "0", "jenkins-nodes", "jenkins-nodes"),
                containers: [containerTemplate(name: "ubuntu",
                                               image: conf.POD_IMAGE_1804,
                                               command: "cat",
                                               ttyEnabled: true)],
                volumes: [hostPathVolume(hostPath: '/var/run/dindproxy/docker.sock',
                                         mountPath: '/var/run/docker.sock')]) {
        node(label){
            container("ubuntu"){
                HELM_IMAGES_HOME = "${WORKSPACE}/openstack-helm-images"

                stage("Checkout"){
                    gerrit.cloneToBranch(HELM_IMAGES_URL,
                                        IMAGE_TAG,
                                        HELM_IMAGES_HOME)
                }

                stage('Setup environment'){
                    sh "apt-get update"
                    sh "apt-get install make sudo docker.io -y"
                }

                stage('Build') {
                    dir ("${HELM_IMAGES_HOME}/${JOB_BASE_NAME}") {
                        UPDATED_IMAGE_TAG = "${IMAGE_TAG}-${SUFFIX}.${BUILD_TIMESTAMP}"
                        IMAGE = "${DOCKER_REGISTRY}/${IMAGE_PREFIX}/${JOB_BASE_NAME}:${UPDATED_IMAGE_TAG}"

                        sh """docker build -f Dockerfile.${SUFFIX} --network host \
                                ${BUILD_ARGS.join(' ')} ${EXTRA_BUILD_ARGS.join(' ')} \
                                -t ${IMAGE} ."""
                    }
                }
                stage('Image Publish'){
                    publish.artifactory (IMAGE, "${IMAGE_PREFIX}/${JOB_BASE_NAME}:${UPDATED_IMAGE_TAG}")

                    if (GERRIT_EVENT_TYPE == 'change-merged') {
                        publish.artifactory (IMAGE, IMAGE_LATEST)
                    }
                }
            }
        }
    }
    // catch both errors and exceptions
} catch (Throwable err) {
    currentBuild.result = 'FAILURE'
    if (env.GERRIT_EVENT_TYPE == 'change-merged') {
        email.sendMail(recipientProviders: [developers(), requestor()],
                       to: env.EMAIL_LIST)
    }
    throw err
}
