MAGE_TAG="${GERRIT_PATCHSET_REVISION}"
DOCKER_REGISTRY="${ARTF_DOCKER_URL}"
IMAGE_PREFIX="openstack-helm-images"
IMAGE_LATEST = "${IMAGE_PREFIX}/${JOB_BASE_NAME}:latest"
VERSION=1.0
HELM_IMAGES_URL = "https://git.openstack.org/openstack/openstack-helm-images"
HELM_IMAGES_HOME = ""

currentBuild.displayName = "#${BUILD_NUMBER} ${GERRIT_EVENT_TYPE}"
if(env.GERRIT_NEWREV){
    echo ("${GERRIT_NEWREV} is being used to override refspec: ${GERRIT_REFSPEC}")
    IMAGE_TAG=env.GERRIT_NEWREV
}
IMAGE="${DOCKER_REGISTRY}/${IMAGE_PREFIX}/${JOB_BASE_NAME}:${IMAGE_TAG}"

vm() {
    HELM_IMAGES_HOME = "${WORKSPACE}/charts"
    currentBuild.displayName = "#${BUILD_NUMBER} ${GERRIT_EVENT_TYPE}"

    stage("Checkout"){
        if(env.GERRIT_NEWREV){
            echo ("${GERRIT_NEWREV} is being used to override refspec: ${GERRIT_REFSPEC}")
            IMAGE_TAG=env.GERRIT_NEWREV
            IMAGE="${DOCKER_REGISTRY}/${IMAGE_PREFIX}/${JOB_BASE_NAME}:${IMAGE_TAG}"
        }
        gerrit.cloneToBranch(HELM_IMAGES_URL,
                             IMAGE_TAG,
                             HELM_IMAGES_HOME)
            // if(GERRIT_EVENT_TYPE != 'change-merged') {
            // sh '''git config user.email "attcomdev.jenkins@gmail.com"
            //    git config user.name "Jenkins"
            //    git pull --rebase origin master'''
            // }
    }

    stage('Setup environment'){
        sh "sudo apt-get update"
        sh "sudo apt-get install make -y"
        vm2.setproxy()
    }

    stage('Build') {
        sh """sudo make IMAGE_NAME=ceph-daemon \
              USE_PROXY=true PROXY=${HTTP_PROXY} \
              IMAGE_PREFIX=${IMAGE_PREFIX} IMAGE_NAME=${JOB_BASE_NAME} \
              DOCKER_REGISTRY=${ARTF_DOCKER_URL} \
              LABEL='org.label-schema.vcs-ref=${IMAGE_TAG} --label org.label-schema.vcs-url=${GERRIT_CHANGE_URL} --label org.label-schema.version=${VERSION}-${BUILD_NUMBER} --label org.label-schema.vcs-event=${GERRIT_EVENT_TYPE}' \
              IMAGE_TAG=${IMAGE_TAG}"""
    }

    stage('Image Publish'){
        publish.artifactory (IMAGE, "${IMAGE_PREFIX}/${JOB_BASE_NAME}:${IMAGE_TAG}")
        if (GERRIT_EVENT_TYPE == 'change-merged') {
            publish.artifactory (IMAGE, IMAGE_LATEST)
        }
    }
}
