import org.yaml.snakeyaml.Yaml
import org.yaml.snakeyaml.DumperOptions;

import groovy.json.JsonSlurperClassic


JENKINS_SLAVE_BUILDER = 'genesis-builder'

GENESIS_NODE_NAME = "genesis"
GENESIS_NODE_IP = '10.24.20.100'
VMX_NODE_NAME = "vmx"
VMX_NODE_IP = '10.24.20.101'

PROMENADE_IMAGE='quay.io/attcomdev/promenade:v0.2.2'
ARMADA_IMAGE='quay.io/attcomdev/armada:master'

DRYDOCK_IMAGE='10.24.20.19:30092/cicd/ucp/ks3019/drydock:ps380732v12'
DRYDOCK_CHART_REPO='https://github.com/sh8121att/helm_charts'
DRYDOCK_CHART_BRANCH='master'

// site manifest repos structure
MANIFEST_PREFIX='region/atl-lab1'
PROMENADE_CFG="${MANIFEST_PREFIX}/ucp/promenade.yaml"
ARMADA_CFG="${MANIFEST_PREFIX}/ucp/armada.yaml"
DRYDOCK_CFG="${MANIFEST_PREFIX}/ucp/drydock.yaml"
ARMADA_OSH_CFG="${MANIFEST_PREFIX}/osh/armada.yaml"

GENESIS_TMPL = "${MANIFEST_PREFIX}/genesis/bootstrap/genesis.yaml"
VMX_TMPL = "${MANIFEST_PREFIX}/vmx/vmx.yaml"


node(JENKINS_SLAVE_BUILDER) {

    // genesis.yaml
    checkout poll: false,
        scm: [$class: 'GitSCM',
            branches: [[name: '$CLCP_INTEGRATION_REFSPEC']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[$class: 'RelativeTargetDirectory',
                relativeTargetDir: 'clcp-integration']],
            submoduleCfg: [],
            userRemoteConfigs: [[refspec: 'refs/changes/*:refs/changes/*',
                url: 'ssh://jenkins-attcomdev@10.24.20.18:29418/clcp-integration',
                    credentialsId:'jenkins-stage-master']]]

    // funcs.groovy
    checkout poll: false,
        scm: [$class: 'GitSCM',
            branches: [[name: '$CICD_GERRIT_REFSPEC']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[$class: 'RelativeTargetDirectory',
                relativeTargetDir: 'cicd']],
            submoduleCfg: [],
            userRemoteConfigs: [[refspec: 'refs/changes/*:refs/changes/*',
                url: 'https://review.gerrithub.io/att-comdev/cicd']]]

    def funcs = load "${WORKSPACE}/cicd/integration/genesis-integration/funcs.groovy"

    funcs.jenkins_slave_destroy(GENESIS_NODE_NAME)
    funcs.jenkins_slave_launch(GENESIS_NODE_NAME,
        "${WORKSPACE}/clcp-integration/${GENESIS_TMPL}", GENESIS_NODE_IP)

    funcs.jenkins_slave_destroy(VMX_NODE_NAME)
    funcs.jenkins_slave_launch(VMX_NODE_NAME,
        "${WORKSPACE}/clcp-integration/${VMX_TMPL}", VMX_NODE_IP)
}


//// ipmi utils

def ipmi_power_off = {
    withCredentials([usernamePassword(credentialsId: 'integration-ipmi',
                                      usernameVariable: 'IPMI_USERNAME',
                                      passwordVariable: 'IPMI_PASSWORD')]) {
        for (ip = 11; ip <= 14; ip++) {
            opts = "-I lanplus -H 10.23.104.${ip} -U \$IPMI_USERNAME -P \$IPMI_PASSWORD"
            sh ("ipmitool ${opts} chassis power off")
        }
    }
}

stage("Genesis Prepare") {
    node(GENESIS_NODE_NAME) {
        checkout poll: false,
            scm: [$class: 'GitSCM',
            branches: [[name: '$CLCP_INTEGRATION_REFSPEC']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [],
            submoduleCfg: [],
            userRemoteConfigs: [[refspec: 'refs/changes/*:refs/changes/*',
                url: 'ssh://jenkins-attcomdev@10.24.20.18:29418/clcp-integration',
                    credentialsId:'jenkins-stage-master']]]

        ipmi_power_off()
    }
}


stage("vMX Prepare") {
    node(GENESIS_NODE_NAME) {
        // any steps need running on vMX
    }
}


def dumpYaml = { cfg ->
    // this sets explicit start for YAML (---)
    DumperOptions options = new DumperOptions();
    options.setExplicitStart(true);

    dump = new Yaml(options).dumpAll(cfg.iterator());
    print dump
    return dump
}


stage("Config Overrides") {
    node(GENESIS_NODE_NAME) {

        // promenade
        def promcfg = readYaml file: "${PROMENADE_CFG}"
        // [0] Cluster
        // [1] Network
        // [2] Version
        promcfg[2].spec.images.armada = ARMADA_IMAGE
        promcfg[2].spec.images.promenade = PROMENADE_IMAGE

        writeFile file: "${PROMENADE_CFG}", text: dumpYaml(promcfg)


        // ucp armada overrides

        def armcfg = readYaml file: "${ARMADA_CFG}"
        def di = -1;
        armcfg.eachWithIndex { value, index ->
            if (value.metadata.name == 'drydock') {
                di = index
                return true // drydock found
            }
        }

        armcfg[di].data.values.images.drydock = DRYDOCK_IMAGE
        armcfg[di].data.values.images.drydock_db_sync = DRYDOCK_IMAGE

        armcfg[di].data.source.location = DRYDOCK_CHART_REPO
        armcfg[di].data.source.reference = DRYDOCK_CHART_BRANCH

        writeFile file: "${ARMADA_CFG}", text: dumpYaml(armcfg)
    }
}


stage("Publish Drydock Site YAML") {
    node(GENESIS_NODE_NAME) {
        spec = """
            {"files": [{
                "pattern": "${MANIFEST_PREFIX}/ucp/drydock.yaml",
                "target": "ucp/drydock/pilot/ucp/drydock.yaml"
            }]}"""

        // drydock doesn't support https
        // artf = Artifactory.server 'artifactory'
        // artf.publishBuildInfo(artf.upload(spec))
    }
}


node(GENESIS_NODE_NAME) {
    stage ("Genesis Deploy Kubernetes") {

        sh "mkdir -p configs"

        opts = "-t -v \$(pwd):/target"
        cmd = "promenade generate -c /target/${PROMENADE_CFG} -o /target/configs"
        sh "sudo docker run ${opts} ${PROMENADE_IMAGE} ${cmd}"

        dir ("configs") {
            sh "sudo bash up.sh genesis.yaml"
        }

        sh 'mkdir -p ~/.kube'
        sh 'cp -r /etc/kubernetes/admin/pki ~/.kube/pki'
        sh 'cat /etc/kubernetes/admin/kubeconfig.yaml | sed -e \'s/\\/etc\\/kubernetes\\/admin/./\' > ~/.kube/config'

        timeout (10) {
            cmd = 'kubectl get pods -n kube-system | grep \'kube-dns\' | grep -e \'3/3\''
            while (sh(returnStatus: true, script: cmd)) sleep 30
        }
        sh "kubectl get pods --all-namespaces"
    }
}

node(GENESIS_NODE_NAME) {

    stage ("Genesis Deploy UCP") {

        sh "kubectl update -f ${MANIFEST_PREFIX}/ucp/rbac-generous-permissions.yaml"

        opts = "-t -v ~/.kube:/armada/.kube -v \$(pwd):/target --net=host"
        topts = "--tiller-host=${GENESIS_NODE_IP} --tiller-port=44134"
        cmd = "apply /target/${ARMADA_CFG}"
        sh "sudo docker run ${opts} ${ARMADA_IMAGE} ${cmd} ${topts}"

        timeout (30) {
            cmd = 'kubectl get pods -n ucp | grep drydock | grep Running |grep -v db | grep -v ks'
            while (sh(returnStatus: true, script: cmd)) sleep 60
        }

        sh "kubectl get pods --all-namespaces"
    }
}


//// maas utils
def maas_import_wait = {
    return
    timeout (10) {
        cmd = 'kubectl get pods -n ucp |grep maas-import'
        while (!sh(returnStatus: true, script: cmd)) sleep 30
    }

    sleep 60 // wait for rack sync
}


//// drydock utils

def keystone_token_get = {

    keystone_image = "kolla/ubuntu-source-keystone:3.0.3"

    docker_env = "-e 'OS_AUTH_URL=http://keystone-api.ucp.svc.cluster.local:80/v3'" +
        " -e 'OS_PROJECT_DOMAIN_NAME=default'" +
        " -e 'OS_USER_DOMAIN_NAME=default'" +
        " -e 'OS_PROJECT_NAME=service'" +
        " -e 'OS_REGION_NAME=RegionOne'" +
        " -e 'OS_USERNAME=drydock'" +
        " -e 'OS_PASSWORD=password'" +
        " -e 'OS_IDENTITY_API_VERSION=3'"

    docker_opts = "--rm --net=host"
    keystone_cmd = "openstack token issue -f value -c id"
    docker_cmd = "sudo docker run ${docker_opts} ${docker_env} ${keystone_image} ${keystone_cmd}"

    return sh(returnStdout: true, script: docker_cmd).trim()
}


def drydock_cmd_run = { token, cmd ->

    drydock_env = "-e 'DD_TOKEN=${token}'" +
        " -e 'DD_URL=http://drydock-api.ucp.svc.cluster.local:9000'" +
        " -e LC_ALL=C.UTF-8" +
        " -e LANG=C.UTF-8"

    drydock_opts = "-v \$(pwd):/target --rm -t --net=host --entrypoint \"drydock\""
    drydock_cmd = "sudo docker run ${drydock_opts} ${drydock_env} ${DRYDOCK_IMAGE}"

    response = sh(returnStdout: true, script: "${drydock_cmd} ${cmd}")
    return new JsonSlurperClassic().parseText(response)
}


def drydock_task_show = { token, task ->
    return drydock_cmd_run(token, "task show --task-id=${task}")
}

,
def drydock_task_create = { token, design, action, interval ->

    task = drydock_cmd_run(token, "task create --design-ref=${design} -a ${action}")

    def status = task.status
    timeout (interval) {
        while (status != 'complete') {
            sleep interval
            r = drydock_task_show(token, task.task_id)
            status = r.status
            print "task -> status: ${r.status}, action: ${r.action}"
        }
    }

    r = drydock_task_show(token, task.task_id).result
    print "task -> status: ${r.status}, result: ${r.result}"

    if (r.status != 'success' && r.status != 'partial_success') {
        print "Failed to execute Drydock task ${task}"
        sh "exit 1"
    }
}


def drydock_web_server = { port ->
    // gap: run nginx for hosting drydock YAMLs
    // this is hack before Artifactory or Deckhand can host YAMLs
    sh "sudo docker run -d -v ${WORKSPACE}:/usr/share/nginx/html -p ${port}:80 nginx"
    return "http://${GENESIS_NODE_IP}:${port}/${DRYDOCK_CFG}"
}


//// drydock provisioning

node(GENESIS_NODE_NAME) {

    stage ("MaaS Import") {
        maas_import_wait(30)
    }

    def design = drydock_web_server('6880')
    def token = keystone_token_get()

    da = ['verify_site', 'prepare_site', 'prepare_nodes', 'deploy_nodes']
    da.each {
        stage ("Drydock (${it})") {
           drydock_task_create (token, design, it, 40)
        }
    }
}


//// armada install openstack

node(GENESIS_NODE_NAME) {
    stage ("Armada Apply") {

        armada_cmd = "apply /target/${ARMADA_OSH_CFG} --tiller-host=${GENESIS_NODE_IP} --tiller-port=44134"
        docker_opts = "-t -v ~/.kube:/armada/.kube -v \$(pwd):/target --net=host"
        docker_cmd = "sudo docker run ${docker_opts} ${ARMADA_IMAGE} ${armada_cmd}"

        //status = sh(returnStatus: true, script: docker_cmd)
        //if (status) {
            // todo: collect logs and handle error
        //    sh "exit 1"
        //}
    }
}

