VM_LAUNCH_NODE = 'local-vm-launch'
NODE_NAME="${JOB_BASE_NAME}-${BUILD_NUMBER}"
NODE_TMPL = "docker/ubuntu.m1.medium.yaml"
IMAGE_PREFIX = env.ARTF_DOCKER_URL+"/ucp/${GERRIT_PROJECT}"

currentBuild.displayName = "${GERRIT_EVENT_TYPE}-${BUILD_NUMBER}"

vm(NODE_NAME, NODE_TMPL) {
    gerrithub.clone($GERRIT_PROJECT,$GERRIT_REFSPEC)
    stage('Build'){
        sh '''sudo make images IMAGE_LIST=${JOB_BASE_NAME}
                             IMAGE_PREFIX=$IMAGE_PREFIX
                             IMAGE_SUFFIX=${JOB_BASE_NAME}
                             IMAGE_TAG=0.1.0.${GERRIT_CHANGE_NUMBER}'''
    }
    stage('Run'){
        sh "docker run ${IMAGE_PREFIX}/${JOB_BASE_NAME}:0.1.0.${GERRIT_CHANGE_NUMBER}"
    }
    stage('Publish'){
        withCredentials([usernamePassword(credentialsId: 'jenkins-artifactory',
                usernameVariable: 'ARTIFACTORY_USER',
                passwordVariable: 'ARTIFACTORY_PASSWORD')]) {
                    opts = '-u $ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD'
                    sh "sudo docker login ${opts} ${env.ARTF_DOCKER_URL}"
                    sh "sudo docker push ${IMAGE_PREFIX}/${JOB_BASE_NAME}:0.1.0.${GERRIT_CHANGE_NUMBER}"
                }
    }
}
