JENKINS_VM_LAUNCH='local-vm-launch'
NODE_NAME="ranger-agent-${BUILD_NUMBER}"
NODE_TMPL="integration/genesis-single.yaml"

IMAGE_TAG= "${GERRIT_PATCHSET_REVISION}"
DOCKER_REGISTRY="${ARTF_DOCKER_URL}"
IMAGE_PREFIX="openstack"
IMAGE_NAME="${IMAGE_PREFIX}/${JOB_BASE_NAME}:${IMAGE_TAG}"
IMAGE_LATEST = "${IMAGE_PREFIX}/${JOB_BASE_NAME}:latest"
QUAY_IMAGE_LATEST="attcomdev/${JOB_BASE_NAME}:latest"
QUAY_IMAGE="attcomdev/${JOB_BASE_NAME}:${IMAGE_TAG}"

IMAGE="${DOCKER_REGISTRY}/${IMAGE_PREFIX}/${JOB_BASE_NAME}:${IMAGE_TAG}"

vm(NODE_NAME, NODE_TMPL) {
    stage('Checkout'){
        sh 'sudo apt-get install make'
        if(env.GERRIT_NEWREV){
            echo ("${GERRIT_NEWREV} is being used to override refspec: ${GERRIT_REFSPEC}")
            IMAGE_TAG=env.GERRIT_NEWREV
            IMAGE="${DOCKER_REGISTRY}/${IMAGE_PREFIX}/${JOB_BASE_NAME}:${IMAGE_TAG}"
            QUAY_IMAGE="attcomdev/${JOB_BASE_NAME}:${IMAGE_TAG}"
        }
        checkout poll: false,
            scm: [$class: 'GitSCM',
              branches: [[name: "${IMAGE_TAG}"]],
              doGenerateSubmoduleConfigurations: false,
              extensions: [[$class: 'LocalBranch',
                            localBranch: 'jenkins'],
                           [$class: 'RelativeTargetDirectory',
                            relativeTargetDir: ""]],
                            submoduleCfg: [],
                            userRemoteConfigs: [[refspec: "${GERRIT_REFSPEC}",
                                                 url: "https://git.openstack.org/${IMAGE_PREFIX}/${JOB_BASE_NAME}"]]]
        if (GERRIT_EVENT_TYPE == 'change-merged') {
            sh '''git config user.email "attcomdev.jenkins@gmail.com"
                  git config user.name "Jenkins"
                  git pull --rebase origin master'''
        }

        currentBuild.displayName = "#${BUILD_NUMBER} ${GERRIT_EVENT_TYPE}"
    }

    stage('Docker Build') {
        timeout(20){
            sh "sudo make images IMAGE_PREFIX=${IMAGE_PREFIX} DOCKER_REGISTRY=${ARTF_DOCKER_URL} LABEL='org.label-schema.vcs-ref=${IMAGE_TAG} --label org.label-schema.vcs-url=${GERRIT_CHANGE_URL} --label org.label-schema.version=0.1.0' IMAGE_TAG=${IMAGE_TAG}"
        }
    }

    stage('Docker Run') {
        timeout(20){
           sh "sudo docker run ${IMAGE}"
        }
    }

    stage('Publish'){
        publish.artifactory (IMAGE, "${IMAGE_PREFIX}/${JOB_BASE_NAME}:${IMAGE_TAG}")
        publish.quay (IMAGE, QUAY_IMAGE)
        if (GERRIT_EVENT_TYPE == 'change-merged') {
            publish.artifactory (IMAGE, IMAGE_LATEST)
            publish.quay (IMAGE, QUAY_IMAGE_LATEST)
        }
    }
}