currentBuild.displayName = "#${BUILD_NUMBER}-${GERRIT_EVENT_TYPE}"
DRYDOCK_COMMIT=""

vm(flavor: "m1.large"){
    sh ('hostname')
    stage('Setup environment'){
        vm2.setproxy()
    }

    stage('Infra Helm Checkout'){

        if ("${GERRIT_PROJECT}" == "${INFRA_PROJECT}" && "${GERRIT_EVENT_TYPE}" == "change-merged"){
            sh 'echo Openstack-helm-infra ${GERRIT_NEWREV} just merged'
            gerrit.cloneToBranch("https://git.openstack.org/${INFRA_PROJECT}", "${GERRIT_NEWREV}","openstack-helm-infra")
            dir("${WORKSPACE}/openstack-helm-infra"){
                HELM_TOOLKIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            }
        }else {
            sh 'mkdir -p openstack-helm-infra'
            dir("${WORKSPACE}/openstack-helm-infra") {
                git branch: "master", url: "https://git.openstack.org/${INFRA_PROJECT}"
                sh "git checkout ${OPENSTACK_HELM_INFRA_COMMIT}"
                HELM_TOOLKIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            }
        }
    }
    stage('Drydock Checkout'){
        if ("${GERRIT_PROJECT}" == "${DRYDOCK_PROJECT}" && "${GERRIT_EVENT_TYPE}" != "change-merged") {
            sh 'echo Drydock commit SHA: ${GERRIT_PATCHSET_REVISION}'
            gerrit.cloneToBranch("https://git.openstack.org/${DRYDOCK_PROJECT}", "${GERRIT_PATCHSET_REVISION}", "${JOB_BASE_NAME}")
        }else if ("${GERRIT_PROJECT}" == "${DRYDOCK_PROJECT}" && "${GERRIT_EVENT_TYPE}" == "change-merged"){
            sh 'echo Drydock commit SHA: ${GERRIT_NEWREV}'
            gerrit.cloneToBranch("https://git.openstack.org/${DRYDOCK_PROJECT}", "${GERRIT_NEWREV}", "${JOB_BASE_NAME}")
        }else{
            sh 'mkdir -p ${JOB_BASE_NAME}'
            dir("${WORKSPACE}/${JOB_BASE_NAME}") {
                git "https://git.openstack.org/${DRYDOCK_PROJECT}"
                sh "git checkout master"
            }
        }
        dir("${WORKSPACE}/${JOB_BASE_NAME}"){
            DRYDOCK_COMMIT = sh(returnStdout: true, script: 'git rev-parse --short=12 HEAD').trim()
            sh "echo Chart version: ${DRYDOCK_COMMIT}.${HELM_TOOLKIT_COMMIT}"
        }
    }
    dir("${WORKSPACE}/${JOB_BASE_NAME}"){
        stage('Build & Package'){
            sh 'sudo apt update'
            sh 'sudo apt-get install -y make'
            def status = sh(returnStatus: true, script: "sudo make charts HTK_COMMIT=${HELM_TOOLKIT_COMMIT}")
            if (status != 0) {
                currentBuild.result = 'FAILED'
                notify.msg("Charts build failed for Drydock SHA: ${DRYDOCK_COMMIT} " +
                        "and Helm toolkit SHA: ${HELM_TOOLKIT_COMMIT}")
            }else{
                notify.msg("Charts were built for Drydock SHA: ${DRYDOCK_COMMIT} " +
                        "and Helm toolkit SHA: ${HELM_TOOLKIT_COMMIT}")
            }
        }
        stage('Rename tarballs') {

            sh("rename s/0.1.0/${DRYDOCK_COMMIT}.${HELM_TOOLKIT_COMMIT}/g ./*")
        }
        stage('Publish'){
            ARTF_REPO="airship-helm-local/airship"
            if("${GERRIT_EVENT_TYPE}" != "change-merged"){
                ARTF_REPO="${ARTF_REPO}/test"
            }
            publish.putArtifacts("drydock*.tgz", "${ARTF_REPO}/drydock/")
            notify.msg("Chart for ${DRYDOCK_COMMIT}.${HELM_TOOLKIT_COMMIT} pushed to ${ARTF_REPO}/drydock")
        }
    }
}
